name: Workflow Dispatch

on:
  push:
    branches: [ 
      "main",
      "staging"
     ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC (Terraform)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::075091538636:role/github-oidc-terraform
          aws-region: us-east-1

      - name: Terraform Init, Plan, and Apply (Staging)
        if: github.ref == 'refs/heads/staging'
        working-directory: ./infra/environments/staging
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Terraform Init, Plan, and Apply (Prod)
        if: github.ref == 'refs/heads/main'
        working-directory: ./infra/environments/prod
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
        

  frontend:
    runs-on: ubuntu-latest
    needs: terraform
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.6.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Tests
        run: npm run test -- --coverage
        working-directory: ./frontend

      - name: Build React app (Staging)
        if: github.ref == 'refs/heads/staging'
        run: npm run build -- --mode staging
        working-directory: ./frontend

      - name: Build React app (Prod)
        if: github.ref == 'refs/heads/main'
        run: npm run build -- --mode production
        working-directory: ./frontend

      - name: Configure AWS credentials via OIDC (Frontend)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::075091538636:role/GitHubActionsFrontendRole
          aws-region: us-east-1

      - name: Sync build to S3 (Staging)
        if: github.ref == 'refs/heads/staging'
        run: aws s3 sync ./frontend/dist/ s3://staging.ghaith-magherbi.com/ --delete

      - name: Sync build to S3 (Prod)
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync ./frontend/dist/ s3://ghaith-magherbi.com/ --delete

      - name: Invalidate CloudFront cache (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1HNB6O82BED0P \
            --paths "/*"
      
      - name: Invalidate CloudFront cache (Prod)
        if: github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1PFBLSJY0JJNI \
            --paths "/*"
